#마크다운 연습
'#'은가장큰 제목
##두번째 큰제목
###세번째 큰제목

이렇게 글을 작성할 수 있음
막이렇게 쓰면 글이 안띄워짐
그럴땐 스페이스바 두번  
그럼 띄워짐  
문단 바꿀 땐

두번 줄 띄움  
```
print('hello world!')
for i in range(10):
  print(i)
```
이러면 코드 블럭  
값을 출력하고 싶으면 `print` 함수 사용  
구분선 위  
---
구분선 아래  
아주 이지 하구만  


#2-1 Tokenization (토큰화)  
Tokenization이란 주어진 corpus에서 token이라 불리는 단위로 나누는 작업을 뜻 함.  

token의 단위는 상황에 따라 다름  
이 장에서 여러가지 상황으로 Tokenization에 대한 개념을 이해할 것임.

##1. 단어 토큰화(Word Tokenization)
token의 단위를 word로 하는 경우.  
이때 word는 단어 단위 외에도 **단어구, 의미를 갖는 문자열**로도 간주함.


예로는 구두점(punctuation)과 같은 문자는 제외하고, 단어들만 tokenization 함.

##2. 토큰화 중 생기는 선택의 순간
tokenization의 기준을 생각해봐야 하는 경우가 발생함.  
예로 들면 ``아포스트로피(`)``가 있음  

토큰화 과정을 예시를 통해 알아볼 예정  

**NLTK**는 영어 코퍼스를 토큰화하기 위한 도구를 제공함.  
`nltk.tokenize`에는 `word_tokenize`와 `WordPunctTokenizer`가 있음.  
이 두개로 어떻게 토큰화를 하는지 알아보자.

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer

In [ ]:
print('단어 토큰화1 :',word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))
print('단어 토큰화2 :',WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

단어 토큰화1 : ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']
단어 토큰화2 : ['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


일단 둘의 차이를 보자.  
`word_tokenize`는 Don\`t를 Do와 n\`t로 분리 하였으나  
Jone\`s는 Jone과 \`s로 분리함.  
`WordPunctTokenizer`은 Don\`t를 Don과 n\`t로 분리 하였으나  
Jone\`s는 Jone과 \`와 s로 분리함.  

이 둘의 차이점은 확실하다.  

keras에서도 토큰화 도구인 `text_to_word_sequence`를 지원함.



In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
print('단어 토큰화3 :',text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

단어 토큰화3 : ["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


`text_to_word_sequence`는 Don\`t와 Jone\`s를 그대로 토큰화 함.  
하지만 전부 소문자화 하였음.  
구두점도 전부 삭제 되었다.  



##3. 토큰화에서 고려해야할 사항
단순희 구두점과 공백을 기준으로 잘라내는 작업이라 보기 어려움.  

###1) 구두점이나 특수 문자를 단순 제외해서는 안된다.
날짜나 소수점이 있는 숫자는 기호를 없애면 의미가 달라짐  

###2) 줄임말과 단어 내에 띄어쓰기가 있는 경우.
띄어쓰기가 있어도 하나의 토큰으로 봐야하는 경우도 있을 수 있음.

###3) 표준 토큰화 예제
**Penn Treebank Tokenization**  
rule 1. 하이푼으로 구성된 단어는 하나로 유지.  
rule 2. doesn`t와 같이 아포스트로피로 '접어'가 함께하는 단어는 분리해준다.  

In [ ]:
from nltk.tokenize import TreebankWordTokenizer

tokenizer = TreebankWordTokenizer()

text = "Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."
print('트리뱅크 워드토크나이저 :',tokenizer.tokenize(text))
#dose + n`t   home-based

트리뱅크 워드토크나이저 : ['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


##4. 문장 토큰화(Sentence Tokenization)
토큰의 단위가 문장일 경우  
  
.을 기준으로 하기엔 문장에 너무 .이 많이 나옴.  
그래서 `sent_tokenize`라는 함수 사용.  
알아서 .이 많아도 문장으로 토큰화 해줌.

In [ ]:
from nltk.tokenize import sent_tokenize

text = "His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
print('문장 토큰화1 :',sent_tokenize(text))


문장 토큰화1 : ['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


In [ ]:
text = "I am actively looking for Ph.D. students. and you are a Ph.D student."
print('문장 토큰화2 :',sent_tokenize(text))


문장 토큰화2 : ['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


방금 영어로 한 문장 토큰화를 한글에도 적용해보자.  
한글은 영어에 비해 까다로움.  

`KSS`로 문장 토큰화 진행.

In [ ]:
!pip install kss

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 1.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.3/131.3 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.4/26.4 MB 42.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for kss: filename=kss-4.5.4-py3-none-any.whl size=54464 sha256=d2d8ea8dc26069ce5a175324526c8278421c23900372f6e3b982442d499300ea
  Stored in directory: /root/.cache/pip/wheels/61/7b/ba/e620ef5d96a61cdd83bdee4c2bb4aec8a74de5d72fcbb00e80
  Created wheel for pecab: filename=pecab-1.0.8-py3-none-any.whl size=26646664 sha256=ac07ffaa58d8e7628c1180d5d2d6068bd2d718c682ac353eb72fed8d3ba98f66
  Stored in directory: /root/.cache/pip/wheels/5c/6f/b4/ab61b8863d7d8b1409def8ae31adcaa089fa91b8d022ec309d
Successfully built kss pecab


In [ ]:
import kss

text = '딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다. 이제 해보면 알걸요?'
print('한국어 문장 토큰화 :',kss.split_sentences(text))


For your information, Kss also supports mecab backend.
We recommend you to install mecab or konlpy.tag.Mecab for faster execution of Kss.
Please refer to following web sites for details:
- mecab: https://github.com/hyunwoongko/python-mecab-kor
- konlpy.tag.Mecab: https://konlpy.org/en/latest/api/konlpy.tag/#mecab-class



한국어 문장 토큰화 : ['딥 러닝 자연어 처리가 재미있기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다.', '이제 해보면 알걸요?']


##5. 한국어에서의 토큰화의 어려움.
조사 같은 단어의 특성때문에 힘이듦.  
띄어쓰기가 잘 지켜지지 않음.  

##6. 품사 태깅(Part-of-speech tagging)
어떤 단어는 여러 뜻을 가지고 있어 품사를 분류하는것은 아주 중요한 일임.

##7. NLTK와 KoNLPy를 이용한 영어, 한국어 토큰화 실습

In [ ]:
#한국어 nlp에서는 영어와 다르게 띄어쓰기 뿐만 아니라 조사도 토큰화 해줘야 함
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
text = "I am actively looking for Ph.D. students. and tou are a Ph.D. student."
tokenized_sentence = word_tokenize(text)

print('단어 토큰화 :',tokenized_sentence)
print('품사 태깅 :',pos_tag(tokenized_sentence))

단어 토큰화 : ['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'tou', 'are', 'a', 'Ph.D.', 'student', '.']
품사 태깅 : [('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('tou', 'NN'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


한국어는 KoNLPy의 `Okt`와 `Kkma`가 있다.

In [ ]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 31.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 40.3 MB/s eta 0:00:00


In [ ]:
from konlpy.tag import Okt
from konlpy.tag import Kkma

okt = Okt()
kkma = Kkma()
print('OKT 형태소 분석 :',okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('OKT 품사 태깅 :',okt.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('OKT 명사 추출 :',okt.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

OKT 형태소 분석 : ['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']
OKT 품사 태깅 : [('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]
OKT 명사 추출 : ['코딩', '당신', '연휴', '여행']


In [ ]:
print('꼬꼬마 형태소 분석 :',kkma.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('꼬꼬마 품사 태깅 :',kkma.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('꼬꼬마 명사 추출 :',kkma.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))


꼬꼬마 형태소 분석 : ['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']
꼬꼬마 품사 태깅 : [('열심히', 'MAG'), ('코딩', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('당신', 'NP'), (',', 'SP'), ('연휴', 'NNG'), ('에', 'JKM'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가보', 'VV'), ('아요', 'EFN')]
꼬꼬마 명사 추출 : ['코딩', '당신', '연휴', '여행']


Okt형태소 분석기와 Kkma형태소 분석기의 결과가 다르게 나옴.  
상황에 따라 다른걸 사용해야함.  
찾아보니 Okt와 Kkma 이외에도 Komoran과 Hannanum이라고 있다.  

특성 비교  

빠른속도와 보통의 정확도 : `Komoran`, `Hannanum`  

속도는 느리더라도 정확하고 상세한 품사 정보 : `Kkma`  

어느 정도의 띄어쓰기가 되어 있는 문장 : `Okt`  
Okt는 띄어쓰기가 안되어있는 문장이면 오래 걸림.

#2-2 Cleaning and Normalization (정제와 정규화)
토큰화 작업 전,후에 텍스트 데이터를 용도에 맞게 **정제 및 정규화**를 해야함.

##1. 표기가 다른 단어들을 하나의 단어로 정규화하기

##2. 대, 소문자 통합  
소문자로 대체하기.  
무작정 한다기보단 문장 맨앞에 오는 대문자만 소문자화  

##3. 불필요한 단어의 제거
등장 빈도가 적거나, 길이가 짧은 단어 삭제  
```
import re
text = "I was wondering if anyone out there could enlighten me on this car."

# 길이가 1~2인 단어들을 정규 표현식을 이용하여 삭제
shortword = re.compile(r'\W*\b\w{1,2}\b')
print(shortword.sub('', text))
```
##4. 정규 표현식

#2-3 Stemming and Lemmatization (어간 추출과 표제어 추출)  
하나의 단어로 일반화 할 수 있다면 하나의 단어로 일반화 해서 단어 수를 줄이는 것.  


##1. 표제어 추출
표제어란 am, are, is의 원형이 be인 것 처럼 그 뿌리 단어가 있는것을 말한다.  

NLTK에서 표제어 추출을 위한 도구인 ```WordNetLemmatizer```을 지원함.

In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']

print('표제어 추출 전 :',words)
print('표제어 추출 후 :',[lemmatizer.lemmatize(word) for word in words])


표제어 추출 전 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
표제어 추출 후 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


dies->dy 이렇게 오류가 발생  
단어의 품사를 수동으로 알려주면 더욱더 정확하게 lemma를 출력함.

In [ ]:
lemmatizer.lemmatize('dies','v')

'die'

In [ ]:
lemmatizer.lemmatize('watched','v')

'watch'

In [ ]:
lemmatizer.lemmatize('has','v')

'have'

##2. 어간 추출(Stemming)
정해진 규칙만 보고 단어의 어미를 자르는 작업 (어림짐작)

In [ ]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

stemmer = PorterStemmer()

sentence = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
tokenized_sentence = word_tokenize(sentence)

print('어간 추출 전 :', tokenized_sentence)
print('어간 추출 후 :',[stemmer.stem(word) for word in tokenized_sentence])

어간 추출 전 : ['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']
어간 추출 후 : ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [ ]:
words = ['formalize', 'allowance', 'electricical']

print('어간 추출 전 :',words)
print('어간 추출 후 :',[stemmer.stem(word) for word in words])


어간 추출 전 : ['formalize', 'allowance', 'electricical']
어간 추출 후 : ['formal', 'allow', 'electric']


```PorterStemmer``` 외에도 ```LancasterStemmer```도 지원함.

In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

porter_stemmer = PorterStemmer()
lancaster_stemmer = LancasterStemmer()

words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print('어간 추출 전 :', words)
print('포터 스테머의 어간 추출 후:',[porter_stemmer.stem(w) for w in words])
print('랭커스터 스테머의 어간 추출 후:',[lancaster_stemmer.stem(w) for w in words])


어간 추출 전 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
포터 스테머의 어간 추출 후: ['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']
랭커스터 스테머의 어간 추출 후: ['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


원하지않는 결과가 나올 수 있으니 결과를 확인 후 알맞는 알고리즘을 선택 해야함.

##3. 한국어에서의 어간 추출


#2-4 Stopword (불용어)
필요없는 단어 제거

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt
stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])


불용어 개수 : 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


In [ ]:
example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example)

result = []
for word in word_tokens:
    if word not in stop_words:
        result.append(word)

print('불용어 제거 전 :',word_tokens)
print('불용어 제거 후 :',result)


불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


한국어에서 불용어 제거

In [ ]:
okt = Okt()

example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "를 아무렇게나 구 우려 고 안 돼 같은 게 구울 때 는"

stop_words = set(stop_words.split(' '))
word_tokens = okt.morphs(example)

result = [word for word in word_tokens if not word in stop_words]

print('불용어 제거 전 :',word_tokens)
print('불용어 제거 후 :',result)


불용어 제거 전 : ['고기', '를', '아무렇게나', '구', '우려', '고', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살', '을', '구울', '때', '는', '중요한', '게', '있지', '.']
불용어 제거 후 : ['고기', '하면', '.', '고기', '라고', '다', '아니거든', '.', '예컨대', '삼겹살', '을', '중요한', '있지', '.']


#2-5 Regular Expression (정규 표현식)
바로 실습 ㄱㄱ

In [ ]:
import re

##.기호
사이에 아무거나 한개가 있음

In [ ]:
r = re.compile("a.c")
r.search("kkk")

In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

##?기호
앞 문자가 있을 수도 있고 없을 수도 있음

In [ ]:
r = re.compile("ab?c")
r.search("abbc")

In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

##*기호
앞 문자가 0개 이상 등장하는지

In [ ]:
 r = re.compile("ab*c")
 r.search("a")

In [ ]:
r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

In [ ]:
r.search("abbbbc")

<re.Match object; span=(0, 6), match='abbbbc'>

##+기호
앞 문자가 하나 이상 등장하는지

In [ ]:
r = re.compile("ab+c")
r.search("ac")

In [ ]:
r.search("abbc")

<re.Match object; span=(0, 4), match='abbc'>

##^기호
^는 문자열의 시작을 의미  
뒤에 오는 문자로 시작하는 단어를 감지

In [ ]:
r = re.compile("^ab")
r.search("bbc")

In [ ]:
r.search("abz")

<re.Match object; span=(0, 2), match='ab'>

##{숫자} 기호
앞 문자가 숫자만큼 반복함

In [ ]:
r = re.compile("ab{2}c")
r.search("ac")

In [ ]:
r.search("abbc")

<re.Match object; span=(0, 4), match='abbc'>

##{숫자,숫자} 기호
앞문자 개수가 숫자 이상 숫자 이하 오면 매칭

In [ ]:
r = re.compile("ab{2,8}c")
r.search("ac")

In [ ]:
r.search("abbbc")

<re.Match object; span=(0, 5), match='abbbc'>

##{숫자,} 기호
앞문자의 개수가 숫자이상 일때 매칭

In [ ]:
r = re.compile("a{2,}bc")
r.search("bc")

In [ ]:
r.search("aaaabc")

<re.Match object; span=(0, 6), match='aaaabc'>

##[] 기호
대괄호 안에 들어가있는 문자 매치  
-를 활용해서 범위를 지정하는 것도 가능함.

In [ ]:
r = re.compile("[abc]")
r.search("zzz")

In [ ]:
r.search("a")

<re.Match object; span=(0, 1), match='a'>

In [ ]:
r.search("ba")

<re.Match object; span=(0, 1), match='b'>

In [ ]:
r = re.compile("[a-z]")
r.search("aBD")

<re.Match object; span=(0, 1), match='a'>

##[^문자] 기호
^뒤에 문자를 제외한 문자를 매치함.

In [ ]:
r = re.compile("[^abc]")
r.search("a")
r.search("ab")

In [ ]:
r.search("d")

<re.Match object; span=(0, 1), match='d'>

##내장함수 예제

###match()와 search()의 차이
match는 문자열의 시작패턴이 같아야 매치  
seach는 문자열 모든곳에서 패턴 매치

In [ ]:
r = re.compile("ab.")
r.match("kkkabc")

In [ ]:
r.search("kkkabc")

<re.Match object; span=(3, 6), match='abc'>

In [ ]:
r.match("abckkk")

<re.Match object; span=(0, 3), match='abc'>

###split()
지정 문자를 기준으로 문자열을 분리

In [ ]:
text = "딸기 당근 수박 참외 메론"
re.split(" ",text)

['딸기', '당근', '수박', '참외', '메론']

###findall()
문자열 내에 정규표현식에 매치되는 모든 문자열을 리스트로 반환함.

In [ ]:
text = "010-5156-8682"
r = re.compile("\d+")
r.search(text)

<re.Match object; span=(0, 3), match='010'>

In [ ]:
re.findall("\d+",text)

['010', '5156', '8682']

###sub()
정규표현식에 해당되는 문자열을 다른문자열로 대체함.

In [ ]:
text ="Regular expression : A regular expression, regex or regexp[1] (sometimes called a rational expression)[2][3] is, in theoretical computer science and formal language theory, a sequence of characters that define a search pattern."

s_text = re.sub("[^a-zA-Z]"," ",text)
print(s_text)

Regular expression   A regular expression  regex or regexp     sometimes called a rational expression        is  in theoretical computer science and formal language theory  a sequence of characters that define a search pattern 


##정규표현식 예제

In [ ]:
text = """100 John    PROF
101 James   STUD
102 Mac   STUD"""

In [ ]:
re.findall("[A-Z]+[a-z]*",text)

['John', 'PROF', 'James', 'STUD', 'Mac', 'STUD']

#2-6 Integer Encoding (정수 인코딩)
단어들을 고유한 숫자에 맵핑하는 것

##1. 정수 인코딩(Integer Encoding)
빈도수가 높은 순서대로 정수를 부여하는 방법

###dictionary 사용

In [4]:
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> ㅇ
Command 'ㅇ' unrecognized

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all


       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package averaged_perceptron_tagger to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger.zip.
       | Downloading package averaged_perceptron_tagger_ru to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger_ru.zip.
       | Downloading package basque_grammars to /root/nltk_data...
       |   Unzipping grammars/basque_grammars.zip.
       | Downloading package bcp47 to /root/nltk_data...
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package bllip_wsj_no_aux to /root/nltk_data...
       |   Unzipping models/bllip_wsj_no_aux.zip.
       | Downloading package book_grammars to /root/nltk_data...
       |   Un


---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [6]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [7]:
raw_text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."


In [8]:
#문장 토큰화
sentences = sent_tokenize(raw_text)
print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [9]:
#문장 정제 및 정규화작업
vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english'))

for sentence in sentences:
  tokenized_sentence = word_tokenize(sentence)
  result = []

  for word in tokenized_sentence:
    word = word.lower() #소문자로 줄이기
    if word not in stop_words:
      if len(word) > 2:
        result.append(word)
        if word not in vocab:
          vocab[word] = 0
        vocab[word]+=1
  preprocessed_sentences.append(result)
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [10]:
print("단어 집합 :",vocab)

단어 집합 : {'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [11]:
print(vocab["barber"])

8


In [12]:
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [13]:
# 빈도가 높은 단어부터 낮은 정수 부여
word_to_index = {}
i = 0
for(word,frequency)in vocab_sorted:
  if frequency>1:
    i+=1
    word_to_index[word]=i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [14]:
# 상위 단어들만 추출

vocab_size = 5
words_frequency = [word for word, index in word_to_index.items() if index >= vocab_size + 1]

for w in words_frequency:
  del word_to_index[w]
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [15]:
# OOV 문제 (단어 집합에 없는 단어)
word_to_index['OOV'] = len(word_to_index) + 1
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


In [17]:
# 정수 인코딩
encoded_sentences = []
for sentence in preprocessed_sentences:
  encoded_sentence = []
  for word in sentence:
    try:
      encoded_sentence.append(word_to_index[word])
    except KeyError:
      encoded_sentence.append(word_to_index['OOV'])
  encoded_sentences.append(encoded_sentence)
print(encoded_sentences)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


###Counter 사용

In [18]:
from collections import Counter

In [19]:
# 토큰화된 리스트를 불러옴
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [21]:
all_words_list = sum(preprocessed_sentences, [])
print(all_words_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [22]:
vocab = Counter(all_words_list)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [24]:
print(vocab["barber"])

8


In [25]:
vocab_size = 5
vocab = vocab.most_common(vocab_size)
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [26]:
word_to_index = {}
i = 0
for(word,frequency) in vocab:
  i+=1
  word_to_index[word] = i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


###NLTK의 FreqDist 사용

In [28]:
from nltk import FreqDist
import numpy as np

In [29]:
vocab = FreqDist(np.hstack(preprocessed_sentences))

In [30]:
print(vocab["barber"])

8


In [31]:
vocab_size=5
vocab = vocab.most_common(vocab_size)
print(vocab)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]


In [32]:
word_to_index = {word[0] : index + 1 for index, word in enumerate(vocab)}
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


##2. Keras의 텍스트 전처리

In [33]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [34]:
preprocessed_sentences =[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [35]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(preprocessed_sentences)

In [38]:
#바로 정수 인코딩
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [40]:
#빈도수 체크
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [42]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [43]:
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size +1)
tokenizer.fit_on_texts(preprocessed_sentences)

In [44]:
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [45]:
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [48]:
# 5개가 적용이 안됌.
print(tokenizer.texts_to_sequences(preprocessed_sentences))
#여기서는 적용된걸 알 수 있다.

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [49]:
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 2, oov_token = 'OOV')
tokenizer.fit_on_texts(preprocessed_sentences)

In [52]:
print(tokenizer.word_index['OOV'])
#기본적으로 OOV의 인덱스를 1로 하고있음

1


In [53]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))
#출력을 보면 알다 시피 2~6으로 인코딩이 된걸 알 수 있다.

[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


#Padding (패딩)
병렬 연산을 위해 길이가 다른 문자열에 임의의 값을 넣어주는 작업이 필요함.

##1. numpy로 하는법

In [55]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [56]:
preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [58]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [59]:
max_len = max(len(item) for item in encoded)
print(max_len)

7


In [60]:
# 길이 맞춰주기
for sentence in encoded:
  while len(sentence) < max_len:
    sentence.append(0)
padded_np = np.array(encoded)
print(padded_np)

[[ 1  5  0  0  0  0  0]
 [ 1  8  5  0  0  0  0]
 [ 1  3  5  0  0  0  0]
 [ 9  2  0  0  0  0  0]
 [ 2  4  3  2  0  0  0]
 [ 3  2  0  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  6  0  0  0  0]
 [ 1  4  2  0  0  0  0]
 [ 7  7  3  2 10  1 11]
 [ 1 12  3 13  0  0  0]]


##keras 전처리 도구로 패딩하기

In [61]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [62]:
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [63]:
padded = pad_sequences(encoded)
padded

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

In [64]:
# 0을 뒤에 채우고 싶다면
padded = pad_sequences(encoded, padding = 'post')
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [65]:
# 어떤 문자열은 막 2000 까지 가는데 다른거를 2000으로 패딩하기엔 엄청난 데이터 손실이
# 일어 날 수 있음
# 그래서 최대를 정해 줄 수 있다.
padded = pad_sequences(encoded, padding ='post', maxlen = 5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]], dtype=int32)

In [66]:
# 삭제 과정은 앞단어를 삭제함
# 만약 뒷단어를 삭제하고 싶다면
padded = pad_sequences(encoded, padding='post', truncating='post', maxlen = 5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 7,  7,  3,  2, 10],
       [ 1, 12,  3, 13,  0]], dtype=int32)

In [68]:
#다른 숫자로 패딩이 가능하다
padded = pad_sequences(encoded, padding = 'post', value = len(tokenizer.word_index)+1)
padded

array([[ 1,  5, 14, 14, 14, 14, 14],
       [ 1,  8,  5, 14, 14, 14, 14],
       [ 1,  3,  5, 14, 14, 14, 14],
       [ 9,  2, 14, 14, 14, 14, 14],
       [ 2,  4,  3,  2, 14, 14, 14],
       [ 3,  2, 14, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  2, 14, 14, 14, 14],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14, 14, 14]], dtype=int32)

#One-Hot Encoding (원-핫 인코딩)
정수인코딩과는 다른 방법

##1. 원-핫 인코딩이란?
정수인코딩 된것을 0과 1로 벡터로 표현

In [69]:
text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

In [70]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
print(tokenizer.word_index)

{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


In [71]:
sub_text = "점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded = tokenizer.texts_to_sequences([sub_text])[0]
print(encoded)

[2, 5, 1, 6, 3, 7]


In [72]:
one_hot = to_categorical(encoded)
print(one_hot)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


##원-핫 인코딩의 한계
단어가 늘어날 수록 필요한 공간이 계속 늘어난다는 단점이 있음.  

또한 유사도를 판별 할 수 없다.  

이러한 단점을 해결하기 위해 다차원 공간에 벡터화 하는 기법이 있음.

#2-9 Splitting Data (데이터의 분리)
데이터를 학습시키고 평가하기 위해서는 적절하게 분리하는 작업이 필요  
지도학습을 위한 데이터 분리작업

In [73]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

##1. 지도 학습(Supercised Learning)
여기서는 학습데이터와 테스트 데이터의 변수를 다음과 같이 선언함.  

X_train : 학습 데이터  
y_train : 학습 데이터의 정답  
X_test : 테스트 데이터  
y_test : 테스트 데어터의 정답  

##2. X와 y 분리하기

###1) zip 함수를 이용하여 분리하기

In [74]:
X, y = zip(['a', 1], ['b', 2], ['c', 3])
print('X 데이터 :',X)
print('y 데이터 :',y)

X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [75]:
# 리스트의 리스트 또는 행렬 또는 뒤에서 배울 개념인 2D 텐서.
sequences = [['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*sequences)
print('X 데이터 :',X)
print('y 데이터 :',y)


X 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


###2) 데이터 프레임 이용

In [76]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df


메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [77]:
X = df['메일 본문']
y = df['스팸 메일 유무']

In [79]:
print(X.to_list())
print(y.to_list())

['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
[1, 0, 0, 1]


###3) Numpy 이용

In [80]:
np_array = np.arange(0,16).reshape((4,4))
print('전체 데이터 :')
print(np_array)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [81]:
X = np_array[:, :3]
y = np_array[:, 3]
print(X)
print(y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[ 3  7 11 15]


##3. 테스트 데이터 분리하기

###1) 사이킷 런을 이용

In [83]:
X,y=np.arange(10).reshape((5,2)), range(5)

print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [87]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=11)

In [88]:
print(X_train)
print(X_test)

[[0 1]
 [6 7]
 [2 3]]
[[4 5]
 [8 9]]


In [89]:
print(y_train)
print(y_test)

[0, 3, 1]
[2, 4]


###2) 수동

In [91]:
X, y= np.arange(0,24).reshape((12,2)), range(12)
num_of_train = int(len(X)*0.8)
num_of_test = int(len(X)-num_of_train)
print(num_of_train)
print(num_of_test)

9
3


In [92]:
X_test = X[num_of_train:]
y_test = y[num_of_train:]
X_train = X[:num_of_train]
y_train = y[:num_of_train]

print(X_test)
print(list(y_test))

[[18 19]
 [20 21]
 [22 23]]
[9, 10, 11]


#2-10 Text Preprocessing Tools for Korean Text (한국어 전처리 패키지)
다양한 패키지들을 알아보자

##1. PyKoSpacing
띄어쓰기가 되어있지 않은 문장을 다시 띄어쓰기 해주는 패키지

In [4]:
# pip install git+https://github.com/haven-jeon/PyKoSpacing.git

In [5]:
sent = '김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.'


In [6]:
new_sent = sent.replace(" ",'')
print(new_sent)

김철수는극중두인격의사나이이광수역을맡았다.철수는한국유일의태권도전승자를가리는결전의날을앞두고10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다.


In [7]:
# from pykospacing import Spacing
# spacing = Spacing()
# kospacing_sent = spaxing(new_sent)

# print(sent)
# print(kospacing_sent)

##2. Py-Hanspell
지금은 잘 작동하지 않음  

띄어쓰기와 맞춤법을 잡아줌

In [10]:
# pip install git+https://github.com/ssut/py-hanspell.git

In [11]:
# from hanspell import spell_shecker

# sent = "맞춤법 틀리면 외 않되? 쓰고싶은대로쓰면돼지 "
# spelled_sent = spell_checker.check(sent)

# hanspell_sent = spelled_sent.checked
# print(hanspell_sent)

##3. SOYNLP를 이용한 단어 토큰화
품사 태깅, 단어 토큰화등을 지원함

In [12]:
pip install soynlp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 416.8/416.8 kB 3.7 MB/s eta 0:00:00


In [14]:
# from konlpy.tag import Okt
# tokenizer = Okt()
# print(tokenizer.morphs('에이비식스 이대휘 1월 최애돌 기부 요정'))

# 기존의 토크나이저는 신조어를 제대로 구분하지 못하는 단점이있음

In [15]:
# import urllib.request
# from soynlp import DoublespaceLineCorpus
# from soynlp.word import WordExtractor


In [16]:
# urllib.request.urlretrieve("https://raw.githubusercontent.com/lovit/soynlp/master/tutorials/2016-10-20.txt", filename="2016-10-20.txt")

In [17]:
# corpus = DoublespaceLineCorpus("2016-10-20.txt")
# len(corpus)

In [18]:
# i = 0
# for document in corpus:
#   if len(document) > 0:
#     print(document)
#     i = i+1
#   if i == 3:
#     break

In [ ]:
# 학습
# word_extractor = WordExtractor()
# word_extractor.train(corpus)
# word_score_table = word_extractor.extract()


SOYNLP의 응집 확률이란  
문자열이 얼마나 응집하여 자주 등장하는지 판단하는 척도이다.  
이를 통해 신조어나 한 단어가 분리되는지 아니면 같이 쓰는 단어인지 판단 할 수 있다.

In [19]:
# word_score_table["반포한"].cohesion_forward

SOYNLP의 브랜칭 엔트로피란  
현재 주어진 단어에서 다음문자가 올 확률이다.

In [20]:
# word_score_table["디스"].right_branching_entropy
# -> 1.6371694761537934
# word_score_table["디스플"].right_branching_entropy
# -> -0.0  (너무 확실해서 0)
# word_score_table["디스플레이"].right_branching_entropy
# -> 3.1400392861792916 (조사가 올 수 있으므로 확률이 작아졌다)

SOYNLP의 L tokenizer 이란  
문장에서 단어 토큰화를 할 때  
단어와 조사가 만난 형태를 tuple로 저장해주는 기법이다.  

왼쪽, 오른쪽으로 나뉘어서 L tokenizer 이라고함

In [21]:
# from soynlp.tokenizer import LTokenizer

# scores = {word:score.cohesion_forward for word, score in word_score_table.items()}
# l_tokenizer = LTokenizer(scores=scores)
# l_tokenizer.tokenize("국제사회와 우리의 노력들로 범죄를 척결하자", flatten=False)

최대 점수 토크나이저란  
띄어쓰기가 되어있지 않은 문장에서 점수가 높은 글자 시퀀스를 찾아내는 토크나이저다.

In [22]:
# from soynlp.tokenizer import MaxScoreTokenizer

# maxscore_tokenizer - MaxScoreTokenizer(scores=scores)
# maxscore_tokenizer.tokenize("국제사회와우리의노력들로범죄를척결하자")

##4. SOYNLP를 이용한 반복되는 문자 정제
ㅋㅋㅋ를 ㅋㅋ로 정제하는 것

In [24]:
# from soynlp.normalizer improt *

In [25]:
# print(emoticon_normalize('앜ㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠㅠ', num_repeats=2))
# print(emoticon_normalize('앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠ', num_repeats=2))
# print(emoticon_normalize('앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠㅠㅠ', num_repeats=2))
# print(emoticon_normalize('앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠㅠㅠㅠㅠ', num_repeats=2))


In [26]:
# print(repeat_normalize('와하하하하하하하하하핫', num_repeats=2))
# print(repeat_normalize('와하하하하하하핫', num_repeats=2))
# print(repeat_normalize('와하하하하핫', num_repeats=2))


##5. Customized KoNLPy
잘못된 토큰화를 바로잡게 수정해주는 패키지다

In [27]:
pip install customized_konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 881.5/881.5 kB 7.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 27.7 MB/s eta 0:00:00


In [29]:
from ckonlpy.tag import Twitter
twitter = Twitter()
twitter.morphs("은경이는 사무실로 갔습니다.")

/usr/local/lib/python3.10/dist-packages/konlpy/tag/_okt.py:17: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')


['은', '경이', '는', '사무실', '로', '갔습니다', '.']

In [30]:
twitter.add_dictionary("은경이","Noun")

In [31]:
twitter.morphs("은경이는 사무실로 갔습니다.")

['은경이', '는', '사무실', '로', '갔습니다', '.']

#2장 총정리