##Tensor

In [1]:
import numpy as np

###Scalar

In [2]:
d = np.array(5)
print(d.ndim)

0


###vector

In [3]:
d = np.array([1,2,3,4])
print(d.ndim)

1


###Matrix

In [4]:
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d.ndim)

2


##벡터 행렬의 연산

In [6]:
A = np.array([8,4,5])
B = np.array([1,2,3])
print(A+B)
print(A-B)

[9 6 8]
[7 2 2]


In [7]:
print(np.dot(A,B))

31


In [8]:
A = np.array([[1, 3],[2, 4]])
B = np.array([[5, 7],[6, 8]])
print(np.matmul(A,B))

[[23 31]
 [34 46]]
